# Generated by Django 5.2.1 on 2025-06-11 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_location', models.CharField(max_length=255)),
                ('attendance_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_monitor', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_is_check_in', models.BooleanField(default=False)),
                ('attendance_is_approved_by_supervisor', models.BooleanField(default=False)),
                ('attendance_is_entry_permitted', models.BooleanField(default=False)),
                ('attendance_is_work_completed', models.BooleanField(default=False)),
                ('attendance_is_equipment_returned', models.BooleanField(default=False)),
                ('attendance_is_overtime_required', models.BooleanField(default=False)),
                ('attendance_is_overtime_approved', models.BooleanField(default=False)),
                ('attendance_is_incomplete_checkout', models.BooleanField(default=False)),
                ('attendance_is_forced_check_out', models.BooleanField(default=False)),
                ('attendance_is_supervisor_checkout', models.BooleanField(default=False)),
                ('attendance_has_been_checkout_by_supervisor', models.BooleanField(default=False)),
                ('attendance_is_supervisor_checkin', models.BooleanField(default=False)),
                ('attendance_is_unauthorized_entry', models.BooleanField(default=False)),
                ('attendance_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_duration_since_supervisor_checkout', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('face_encoding', models.JSONField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('equipment', models.ManyToManyField(blank=True, related_name='equipment', to='faceapp.equipment')),
                ('labourer', models.ManyToManyField(blank=True, related_name='tasks', to='faceapp.worker')),
            ],
        ),
    ]
