# Generated by Django 5.2.1 on 2025-07-15 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.CharField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('face_encoding', models.JSONField()),
                ('role', models.CharField(max_length=100)),
            ],
        ),
    ]
