# Generated by Django 5.2.1 on 2025-07-15 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='role',
            new_name='project_id',
        ),
    ]
