# Generated by Django 5.2.1 on 2025-06-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='person_id',
            field=models.CharField(blank=True, null=True),
        ),
    ]
