# Generated by Django 5.2.1 on 2025-07-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_rename_role_worker_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='project_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
