# Generated by Django 5.2.1 on 2025-05-28 12:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0002_equipment_remove_worker_id_worker_person_id_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.AutoField(primary_key=True, serialize=False)),
                ('attendance_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_location', models.CharField(max_length=255)),
                ('attendance_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_monitor', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_is_check_in', models.BooleanField(default=False)),
                ('attendance_is_approved_by_supervisor', models.BooleanField(default=False)),
                ('attendance_is_entry_permitted', models.BooleanField(default=False)),
                ('attendance_is_work_completed', models.BooleanField(default=False)),
                ('attendance_is_equipment_returned', models.BooleanField(default=False)),
                ('attendance_is_overtime_required', models.BooleanField(default=False)),
                ('attendance_is_overtime_approved', models.BooleanField(default=False)),
                ('attendance_is_incomplete_checkout', models.BooleanField(default=False)),
                ('attendance_is_forced_check_out', models.BooleanField(default=False)),
                ('attendance_is_supervisor_checkout', models.BooleanField(default=False)),
                ('attendance_has_been_checkout_by_supervisor', models.BooleanField(default=False)),
                ('attendance_is_supervisor_checkin', models.BooleanField(default=False)),
                ('attendance_is_unauthorized_entry', models.BooleanField(default=False)),
                ('attendance_access_token', models.CharField(blank=True, max_length=255, null=True)),
                ('attendance_duration_since_supervisor_checkout', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-attendance_timestamp'],
            },
        ),
        migrations.AddField(
            model_name='worker',
            name='role',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
